version: "3.7"

services:
  hstesting:
    image: hstest

    # volumes:
    #   - db_data:/var/lib/postgresql/data
    # expose:
    #   - 5432
    # environment:
    #   POSTGRES_PASSWORD: changeme
    #   POSTGRES_DB: windmill
